=== jakweg/wonder/barbet/enum-schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Enum description",
  "properties": {
    "$schema": true,
    "name": {
      "type": "string",
      "minLength": 1
    },
    "output-file": {
      "type": "string",
      "minItems": 1
    },
    "add-size": {
      "type": "boolean"
    },
    "values": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "type": "object",
          "patternProperties": {
            "^@.*$": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "from": {
                  "type": "string"
                },
                "property": {
                  "type": ["string", "null"]
                }
              },
              "required": ["from", "property"]
            },
            "^.*$": {
              "type": ["string", "number", "boolean"]
            }
          }
        }
      },
      "additionalProperties": false
    },
    "getters": {
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "properties": {
            "field": {
              "type": "string"
            },
            "if-invalid-enum": {
              "enum": ["throw", "return-null", "return-undefined"]
            }
          },
          "additionalProperties": false,
          "required": ["field"]
        }
      },
      "additionalProperties": false
    }
  },
  "required": ["values", "name"],
  "additionalProperties": false
}

=== jakweg/wonder/barbet/src/main/game-state/activities/activities.2bc.json
{
  "$schema": "https://raw.githubusercontent.com/JakubekWeg/wonder/master/barbet/enum-schema.json",
  "name": "ActivityId",
  "output-file": "index",
  "values": {
    "None": {
      "@perform": {
        "from": "./none",
        "property": "perform"
      }
    },
    "Slime_Idle": {
      "@perform": {
        "from": "./slime/idle",
        "property": "perform"
      }
    },
    "Slime_SlowRotate": {
      "@perform": {
        "from": "./slime/slow-rotate",
        "property": "perform"
      }
    },
    "Slime_Jump": {
      "@perform": {
        "from": "./slime/jump",
        "property": "perform"
      }
    }
  },
  "getters": {
    "getActivityPerformFunction": {
      "field": "@perform"
    }
  }
}

=== jakweg/wonder/barbet/src/main/3d-stuff/model/model-id.2bc.json
{
  "$schema": "https://raw.githubusercontent.com/JakubekWeg/wonder/master/barbet/enum-schema.json",
  "name": "ModelId",
  "output-file": "model-id",
  "add-size": true,
  "values": {
    "Slime": {
      "@build": {
        "from": "./entity/slime",
        "property": "buildPoses"
      }
    }
  },
  "getters": {
    "getBuildPosesCallback": {
      "field": "@build"
    }
  }
}
